### ISSUE TITLE
PES 2011 is running slow

### ISSUE THREAD

**Issue by RoberTo-L** [nikita36078/J2ME-Loader#456]
**Emulator version:**
``1.4.2-play``

**Game version:**
``1.0.0``

**Game resolution:**
``320x240``

**Device:**
``Samsung Galaxy J5 Pro``

**Android version:**
``8.1.0``
**Description of the issue:**
The game PES 2011 has crashes in version 1.4.2 of the emulator, this has not happened in previous versions, with the acceleration of HW activated improving a little but the game continues to crash.

**Comment by nikita36078** [comment]
Fixed.

**Comment by jack1432** [comment]
I thought the problem was fixed, but pressing the Back button or changing from portrait to landscape makes the game slow again.

**Comment by RoberTo-L** [comment]
@nikita36078, I installed PES 2011 on the latest version of JL-Mod and, apparently, it worked very well, the game does not become slow when I press Back or change the screen orientation, but on the original J2ME Loader the errors still happen.

**Comment by nikita36078** [comment]
Should work fine now
