### ISSUE TITLE
List of Java Games w/ Glitch (Updated)

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#94]
<a name="Top" id="user-content-top"></a>
	
# **List of Java  Games w/ Glitch**

<b>Nav:</b> [ <a href="#user-content-f">Fixed</a> | <a href="#user-content-nf">Not-Fixed</a> | <a href="#user-content-bot">Bottom</a> ]
	
>\-  List of buggy/unplayable games.

**Game Type:** Touchscreen \- **(T)**, Non\-Touchscreen \- **(NT)**
**Orientation:** Landscape \- **(L)**, Portrait \- **(P)**
**Screenshot:** <a href="#">▣</a> - Click to view.

<h2  id="user-content-f" align="center">Fixed</h2>

| <h3>Game Name</h3> | <h3>Known Bugs</h3> | <h3>Game Type</h3> | <h3>Size</h3> | <h3>Orientation</h3>  | 
| :---         |     :---      |     :---:      |     :---:      | :---:         |  
|1. ~~Block Breaker 3 Unlimited~~|Graphical Bug. [▣](https://user-images.githubusercontent.com/36059629/35844939-e40682d0-0b4a-11e8-8e8a-22b2192b44be.png)<br/>Game via (PC)KEmulator: [▣](https://user-images.githubusercontent.com/36059629/35848599-aaf1c1e4-0b59-11e8-9dd9-ba5be41e6600.png)|T|360x640|P| 
|2. ~~Miami Nights 2~~|Graphical Bug:<br/>\- The title screen's image is not full. [▣](https://user-images.githubusercontent.com/36059629/35887627-e13a58f8-0bcf-11e8-8627-60685d770cc7.jpg)<br/>\- Tried to fix by activating buffered clearing, the title screen's image was fixed but the game's background becomes black and it flickers when touched. [▣](https://user-images.githubusercontent.com/36059629/35888064-63425e4e-0bd1-11e8-8359-d78ba0268005.jpg)|T|640x360|L| 
|3. ~~My Life in New York and World at Arms~~&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;  | Graphical Bug: Arrow buttons.<br/>My Life in New York: [▣](https://user-images.githubusercontent.com/36059629/35889126-382b63f0-0bd5-11e8-8f26-b1f823d61adf.jpg)<br/> World at Arms [▣](https://user-images.githubusercontent.com/36059629/35845251-8dcaa28c-0b4c-11e8-98cd-c3f4b90d64c1.jpg)<br/>World at War via (PC)KEmulator: [▣](https://user-images.githubusercontent.com/36059629/35848059-99a60ae6-0b57-11e8-8baa-ce23280ac2f9.png)|T|640x360|L| 
|4. ~~Splinter Cell~~ |   #96 Repetitive Image.  | NT   | 176x208  | P  |  
|5. ~~Splinter Cell Conviction~~   | #96  Repetitive Image. [▣](https://user-images.githubusercontent.com/22563129/36175011-0fcba2e8-1149-11e8-9cbd-7f50f246ccce.png)| T  |   480x800 |  L |  
|6. ~~Warcraft 3 RUS~~ |  #96  | NT | 240x320  | P  |     
|  7. ~~MU Blood Empire~~ |  Graphical Bug when moving diagonally. [▣](https://user-images.githubusercontent.com/36059629/36263287-d981adba-12a4-11e8-931b-6d4e7f077766.jpg) | NT   |  240x320  | P   | 
|  8. ~~Holy Wars~~  |  #124 (Same issue like arrow button graphical bug from no. 3) Flip barrel. [▣](https://user-images.githubusercontent.com/36059629/36313372-468ddd12-136c-11e8-879f-219d727f3b2b.jpg)<br/>Game via (PC)KEmulator: [▣](https://user-images.githubusercontent.com/36059629/36335970-d76b1834-13be-11e8-93bf-a019aacb878d.png)| NT   |240x320    | P   | 
|  9. ~~God of War~~ |  #119, #124 (Same issue like arrow button graphical bug from no. 3) Flip image, Slow FPS(Recommended Midlet Version for fast fps: 1.4.32) [▣](https://user-images.githubusercontent.com/36059629/36336358-05be2494-13c2-11e8-9fc7-28f147e0ba5e.png)<br/>Game via (PC)KEmulator: [▣](https://user-images.githubusercontent.com/36059629/36336405-6ee1589c-13c2-11e8-8939-47027316b45a.png)|NT    | 240x320  | P   |  
|  10. ~~Dragon Island~~  |   #110 Graphical Bug: Invisible Status. [▣](https://user-images.githubusercontent.com/22563129/36336448-cd22a5d2-13c2-11e8-9542-874c0a6a9538.png)| NT   | 240x320   |  P  | 
|  11. ~~Tower Bloxx 3D~~  |   #120 Texture Problem. | NT   |  240x320  |    P|   
|12. ~~Spore Origins~~|WhiteScreen only|T|640x360|L|
|13. ~~Narnia 3~~| v1.1.0: Game will crash while in loading screen. (Recommended Midlet Version: v1.0.7  for SATIO/Vivaz)  |T|640x360|L|
|    |    |    |     |    |  

<h2 id="user-content-nf"  align="center">Not-Fixed</h2>

| <h3>Game Name</h3> | <h3>Known Bugs</h3> | <h3>Game Type</h3> | <h3>Size</h3> | <h3>Orientation</h3>  | 
| :---         |     :---      |     :---:      |     :---:      | :---:         |  
|1. Gangstar 3: Miami Vindication & Gangstar Rio: City of Saints|  Graphical Bug: <br/>Games are totally playable but the shadows are square instead of circle. [▣](https://user-images.githubusercontent.com/36059629/36123035-661476de-1086-11e8-90fe-f0038ae51de9.jpg)| T | 640x360 | L  | 
|2. Icy Tower Jump|Graphical Bug: Invisible blocks and character. [▣](https://user-images.githubusercontent.com/36059629/36263798-f8b02620-12a5-11e8-9119-dbbd7b5ceb65.jpg) |T|360x640|P|
|3. Midnight Bowling 3| Invisible pins and bowling ball. [▣](https://user-images.githubusercontent.com/36059629/35844677-a1c5380e-0b49-11e8-9dec-9ff83e91afd9.png)<br/>Game via (PC)KEmulator: [▣](https://user-images.githubusercontent.com/36059629/36083692-3a8a8206-0ff0-11e8-8bfa-c8ae57a26b81.png)|T|360x640|P|
|   4. Doom 2 RPG |  #145 Graphical Bug.  |  NT  |  - | P   | 
|5. Real Football 2014-17| Can't be converted, j2me loader will crash while converting|T|640x360|L|
|6. Shrek Forever After|Laggy/Slow FPS even if filter is disabled.|T|360x640|L|
|7. Crazy Penguin, Johny Bravo & How to Train Your Dragon|#106 Flickering Issue, Stuck|T|-|-|
|8. Micro Counter Strike & Other 3D Games | #103 Blank Screen.  |  - |  - | -  | 
|9. WWE Smackdown vs Raw, Need for Speed Shift 3D & Asphalt 3 3D  | #97 3D games have bumpy colors.   | -  |  - |    -| 
|10. Tetris Revolution | #100 Graphical Bug. [▣](https://user-images.githubusercontent.com/22563129/35894530-1acbe51e-0bee-11e8-9596-8dc68d3f03d0.png) | NT   |  240x320 |  P | 
|11. Asphalt 6 | #96 Flickering issue.   |  -  | 480x800  | -  |  
| 12. 4x4 Extreme Rally  | #62 Broken Manifest   |   - |  All Screen Version|-   |  
|  13. Diamond Rush  |  #62 Blank Screen, #125 Error Installing. | -  | All Screen Version | - |
|  14. 3D Crash Arena  |  #62 Arena becomes blank, FPS Drop.  |-   | -  | -  | 
|   15. Tony Hawk Vert |  Graphical Bug, Flickering Issue. [▣](https://user-images.githubusercontent.com/36059629/36258798-039dc484-1297-11e8-9686-3c0203dc04a9.png)|  T  |  640x360 | L   |
|   16. Ice Age 2 - Arctic Slide | Game Crash. [▣](https://user-images.githubusercontent.com/36059629/36262196-b34296ee-12a1-11e8-9402-9bf95f323458.jpg) |  NT | 240x320   |  P | 
|  17. Galaxy on Fire 3D & Galaxy on Fire 2 3D  |    Menu Screen Flicker| NT   |240x320    | P   |  
|   18. Extreme Air Snowboarding 3D | Graphical Bug. [▣](https://user-images.githubusercontent.com/36059629/36297642-d138ea4e-132e-11e8-8b37-3d5dad801250.png)<br/>Game via (PC)KEmulator: [▣](https://user-images.githubusercontent.com/36059629/36297713-4964e518-132f-11e8-83bd-23c7ded52b2a.png)|  NT  | 240x320   |  P |   
|   19. Heroes of War Sandstorm | Graphical Bug, Flickering Issue. [▣](https://user-images.githubusercontent.com/36059629/36269572-68962328-12b4-11e8-9fe5-809c75d50814.png) |  NT | 240x320  | P   |  
|  20. Eon the Dragon 2|  Stuck at loading screen. [▣](https://user-images.githubusercontent.com/36059629/36269840-335ae166-12b5-11e8-8210-c3ca5d1b5e44.png)|  NT | 240x320   |P    |  
|   21. Medieval Combat Age of Glory | #124 Battleground Image Background Bug. [▣](https://user-images.githubusercontent.com/36059629/36289702-6250494c-12fc-11e8-8f1b-09a45ed2c34a.jpg)<br/> Game via (PC)KEmulator: [▣](https://user-images.githubusercontent.com/36059629/36289782-e20f9372-12fc-11e8-9561-11f10bfe7ce2.png) | NT   |   240x320 |   P|  
|   22. Kamikaze 2: Way of Ninja |  #113 Game Crash, Laggy  | NT | 352x416   | P  |  
|  23. Silent Hill 1<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Silent Hill 2 |  #114 Game hangs. |  NT|320x240<br/>240x400  |  L<br/>P  |    
| 24. Rally 3D   |  #117 Graphical Bug. | NT   |  240x320  |  P  |
|   25. Guitar Hero 5 | #118 Slow Fps | T   |   360x640|  -  |      
|  26. Tower Bloxx Revolution | #123 Graphical Bug.    |  T  |  360x640  |  P  | 
|  27. WWE 2010  |  #122 Graphical Bug.  | -   |   - |   -|  
| 28. Crash Bandicoot 2D| #133 Graphical Bug.| NT| -|P |
|  29. Crash Racing |   #132 Hanging Issue. | NT   |  176x220  |  P  | 
|   30. Crash Twinsanity 2D | #131 Startup Error.   |   NT |  176x208  |   P | 
|   31. Crash Nitro Kart 1 |  #130 Startup Error. |    NT|  128x128  |   P | 
|    32. Bounce |  #129 Graphical Bug.  | NT    |   128x128 |  P  | 
|   33. Tomb Raider Legend Tokyo |  #127 Graphical Bug   | NT   |   240x320  | P   | 
|  34. Prince of Persia Classic | #137 Graphical Bug   |NT    |240x320    | P   | 
|  35. Gangstar Crime City  |  #141 Error in Controls.  |   NT | 240x320   | P   | 
|  36. Gish  |  #140 Hanging Problem.  | NT    |    -|   P | 
| 37. Blades and Magic 3D   |  #138 Startup Error.  | NT   |  176x220<br>240x320  |  P  | 
|  38. 3D Rolercoaster Rush Underground  |  #143 Graphical Bug. |  T |   -|  P  | 
| 39. Angry Birds, Rally 3D  |   #144 Sound Issue. |   NT |  240x320  |   P | 
|    |    |    |    |    | 

<a name="Bottom" id="user-content-bot"></a>
	
List of Tested Java Games (Touchscreen): #99 
List of Tested Java Games (Non-Touchscreen): #108

<b>Nav:</b> [ <a href="#user-content-f">Fixed</a> | <a href="#user-content-nf">Not-Fixed</a> | <a href="#user-content-top">Top</a> ]

**Comment by AdityaMH** [comment]
About Brick Breaker 3 Unlimited in your screenshot. just enable "draw buffer clearing" and problem solved.

**Comment by nikita36078** [comment]
I fixed bug in World at Arms, it will be available in the next version.

**Comment by oatmeal01** [comment]
thanks! @nikita, most of gameloft games 360x640/640x340 has an arrow like that. and also i can't fix miami nights with buffered clearing. check the image above

**Comment by nikita36078** [comment]
My Life in NY, Miami Nights, Block Breaker - fixed too.

**Comment by nikita36078** [comment]
@oatmeal01 It looks okay now.

**Comment by oatmeal01** [comment]
@nikita  the latest version on playstore didn't fix the graphics bug but the latest version i downloaded here fixed all the graphics bug. Thanks and more power.

**Comment by nikita36078** [comment]
I deleted all app links, because of #56.

**Comment by oatmeal01** [comment]
how can we provide you the link so that you can test the game? is it okay if we just send it thru  mail

**Comment by nikita36078** [comment]
Game name + resolution is enough for me.

**Comment by nikita36078** [comment]
I think we need to create separate issues for each game, otherwise it will become too complicated in future.

**Comment by oatmeal01** [comment]
you mean separate issue for touchscreen and non-touchscreen games

**Comment by nikita36078** [comment]
I mean separate issue for each game, to prevent people from creating multiple lists with the same games.
